name: activistChatbot

services:
  chatbot:
    image: registry.datacenter.house/activistchatbot:latest
    volumes:
      - chatbot_data:/app/database:Z
    env_file: .env
    restart: always

volumes:
  chatbot_data:
