FROM python:3.14-slim

RUN groupadd -r activistbot && useradd --no-log-init -r -g activistbot activistbot
RUN mkdir -p /app && chown -R activistbot:activistbot /app

WORKDIR /app
COPY container/run.sh /app/container/run.sh
COPY pyproject.toml /app/pyproject.toml
COPY src /app/src

RUN pip install --no-cache-dir uv~=0.8.19
RUN uv --no-cache sync

USER activistbot

CMD [ "/app/container/run.sh" ]
