"""
This type stub file was generated by pyright.
"""

import asyncio
import inspect
import sys
import time
from datetime import datetime
from functools import partial, wraps
from uuid import uuid4

from cronsim import CronSim
from tzlocal import get_localzone

async def null_callback(*args):  # -> tuple[Any, ...]:
    ...
def wrap_func(func):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], CoroutineType[Any, Any, Any]]:
    """wrap in a coroutine"""
    ...

class Cron:
    def __init__(self, spec, func=..., args=..., kwargs=..., start=..., uuid=..., loop=..., tz=...) -> None: ...
    def start(self):  # -> None:
        """Start scheduling"""
        ...

    def stop(self):  # -> None:
        """Stop scheduling"""
        ...

    async def next(self, *args):
        """yield from .next()"""
        ...

    def initialize(self):  # -> None:
        """Initialize cronsim and related times"""
        ...

    def get_next(self):  # -> float:
        """Return next iteration time related to loop time"""
        ...

    def call_next(self):  # -> None:
        """Set next hop in the loop. Call task"""
        ...

    def call_func(self, *args, **kwargs):  # -> None:
        """Called. Take care of exceptions using gather"""
        ...

    def set_result(self, result):  # -> None:
        """Set future's result if needed (can be an exception).
        Else raise if needed."""
        ...

    def __call__(self, func):  # -> Self:
        """Used as a decorator"""
        ...

    def __str__(self) -> str: ...
    def __repr__(self):  # -> str:
        ...

def crontab(spec, func=..., args=..., kwargs=..., start=..., loop=..., tz=...):  # -> Cron:
    ...
