"""
This type stub file was generated by pyright.
"""

import unittest
from unittest.mock import AsyncMock, MagicMock
from signalbot.bot import Command, Context

def chat(*messages): # -> Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], CoroutineType[Any, Any, Any]]]:
    ...

class ChatTestCase(unittest.IsolatedAsyncioTestCase):
    signal_service = ...
    phone_number = ...
    group_id = ...
    group_secret = ...
    config = ...
    def setUp(self): # -> None:
        ...
    
    async def run_bot(self): # -> None:
        ...
    
    @classmethod
    def new_message(cls, text) -> str:
        ...
    


class ReceiveMessagesMock(MagicMock):
    def define(self, messages: list): # -> None:
        ...
    


class SendMessagesMock(AsyncMock):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def results(self) -> list:
        ...
    


class ReactMessageMock(AsyncMock):
    def results(self) -> list:
        ...
    


class DummyCommand(Command):
    async def handle(self, context: Context): # -> None:
        ...
    


