"""
This type stub file was generated by pyright.
"""

import aiohttp
from typing import Any, Literal, TYPE_CHECKING
from collections.abc import AsyncIterator

if TYPE_CHECKING:
    ...
class SignalAPI:
    def __init__(self, signal_service: str, phone_number: str, download_attachments: bool = ...) -> None:
        ...
    
    async def receive(self) -> AsyncIterator[str]:
        ...
    
    async def send(self, receiver: str, message: str, *, base64_attachments: list | None = ..., link_preview: dict[str, Any] | None = ..., quote_author: str | None = ..., quote_mentions: list | None = ..., quote_message: str | None = ..., quote_timestamp: int | None = ..., mentions: list[dict[str, Any]] | None = ..., text_mode: str | None = ..., edit_timestamp: int | None = ..., view_once: bool = ...) -> aiohttp.ClientResponse:
        ...
    
    async def react(self, recipient: str, reaction: str, target_author: str, timestamp: int) -> aiohttp.ClientResponse:
        ...
    
    async def receipt(self, recipient: str, receipt_type: Literal["read", "viewed"], timestamp: int) -> aiohttp.ClientResponse:
        ...
    
    async def start_typing(self, receiver: str) -> aiohttp.ClientResponse:
        ...
    
    async def stop_typing(self, receiver: str) -> aiohttp.ClientResponse:
        ...
    
    async def get_groups(self) -> list[dict[str, Any]]:
        ...
    
    async def get_attachment(self, attachment_id: str) -> str:
        ...
    
    async def delete_attachment(self, attachment_id: str) -> str:
        ...
    
    async def update_contact(self, receiver: str, expiration_in_seconds: int | None = ..., name: str | None = ...) -> None:
        ...
    
    async def update_group(self, group_id: str, base64_avatar: str | None = ..., description: str | None = ..., expiration_in_seconds: int | None = ..., name: str | None = ...) -> None:
        ...
    
    async def health_check(self) -> aiohttp.ClientResponse:
        ...
    
    async def check_signal_service(self) -> bool:
        ...
    
    async def get_signal_cli_rest_api_version(self) -> str:
        ...
    
    async def remote_delete(self, receiver: str, timestamp: int) -> aiohttp.ClientResponse:
        ...
    


class SignalAPIURIs:
    def __init__(self, signal_service: str, phone_number: str, use_https: bool = ...) -> None:
        ...
    
    @property
    def https_or_http(self) -> str:
        ...
    
    @property
    def wss_or_ws(self) -> str:
        ...
    
    def attachment_rest_uri(self) -> str:
        ...
    
    def receive_ws_uri(self) -> str:
        ...
    
    def send_rest_uri(self) -> str:
        ...
    
    def react_rest_uri(self) -> str:
        ...
    
    def typing_indicator_uri(self) -> str:
        ...
    
    def groups_uri(self) -> str:
        ...
    
    def group_id_uri(self, group_id: str) -> str:
        ...
    
    def contacts_uri(self) -> str:
        ...
    
    def health_check_uri(self) -> str:
        ...
    
    def receipts_rest_uri(self) -> str:
        ...
    
    def remote_delete_uri(self) -> str:
        ...
    
    def about_rest_uri(self) -> str:
        ...
    


class ReceiveMessagesError(Exception):
    ...


class SendMessageError(Exception):
    ...


class TypingError(Exception):
    ...


class StartTypingError(TypingError):
    ...


class StopTypingError(TypingError):
    ...


class ReactionError(Exception):
    ...


class GroupsError(Exception):
    ...


class GetAttachmentError(Exception):
    ...


class ContactUpdateError(Exception):
    ...


class HealthCheckError(Exception):
    ...


class RemoteDeleteError(Exception):
    ...


class SignalServiceConnectionError(Exception):
    ...


class AboutError(Exception):
    ...


