"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import Any, Literal, TYPE_CHECKING, TypeAlias
from signalbot.command import Command
from signalbot.message import Message
from signalbot.link_previews import LinkPreview

if TYPE_CHECKING:
    ...
CommandList: TypeAlias = list[tuple[Command, list[str] | bool, list[str] | bool, Callable[[Message], bool] | None,]]
LOGGER_NAME = ...
def enable_console_logging(level: int = ...) -> None:
    ...

class SignalBot:
    def __init__(self, config: dict) -> None:
        """SignalBot

        Example Config:
        ======= Mandatory fields ========
        signal_service: "127.0.0.1:8080"
        phone_number: "+49123456789"

        ======= Optional fields ========
        storage:
            redis_host: "redis"
            redis_port: 6379
        retry_interval: 1
        download_attachments: True
        """
        ...
    
    def register(self, command: Command, contacts: list[str] | bool = ..., groups: list[str] | bool = ..., f: Callable[[Message], bool] | None = ...) -> None:
        ...
    
    def start(self, run_forever: bool = ...) -> None:
        ...
    
    async def send(self, receiver: str, text: str, *, base64_attachments: list | None = ..., link_preview: LinkPreview | None = ..., quote_author: str | None = ..., quote_mentions: list | None = ..., quote_message: str | None = ..., quote_timestamp: int | None = ..., mentions: (list[dict[str, Any]] | None) = ..., edit_timestamp: int | None = ..., text_mode: str | None = ..., view_once: bool = ...) -> int:
        ...
    
    async def react(self, message: Message, emoji: str) -> None:
        ...
    
    async def receipt(self, message: Message, receipt_type: Literal["read", "viewed"]) -> None:
        ...
    
    async def start_typing(self, receiver: str) -> None:
        ...
    
    async def stop_typing(self, receiver: str) -> None:
        ...
    
    async def update_contact(self, receiver: str, expiration_in_seconds: int | None = ..., name: str | None = ...) -> None:
        ...
    
    async def update_group(self, group_id: str, base64_avatar: str | None = ..., description: str | None = ..., expiration_in_seconds: int | None = ..., name: str | None = ...) -> None:
        ...
    
    async def remote_delete(self, receiver: str, timestamp: int) -> int:
        ...
    
    async def delete_attachment(self, attachment_filename: str) -> None:
        ...
    


class SignalBotError(Exception):
    ...


