"""
This type stub file was generated by pyright.
"""

import re
from abc import ABC, abstractmethod
from typing import Callable, ParamSpec, TYPE_CHECKING, TypeVar
from signalbot.context import Context

T = TypeVar("T")
P = ParamSpec("P")
if TYPE_CHECKING:
    ...
def regex_triggered(*by: str | re.Pattern[str]) -> Callable[[Callable[P, T]], Callable[P, T]]:
    ...

def triggered(*by: str, case_sensitive: bool = ...) -> Callable[[Callable[P, T]], Callable[P, T]]:
    ...

class Command(ABC):
    def __init__(self) -> None:
        ...
    
    def setup(self) -> None:
        ...
    
    def describe(self) -> str | None:
        ...
    
    @abstractmethod
    async def handle(self, context: Context) -> None:
        ...
    


class CommandError(Exception):
    ...


