"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal, TYPE_CHECKING
from signalbot.bot import SignalBot
from signalbot.link_previews import LinkPreview
from signalbot.message import Message

if TYPE_CHECKING:
    ...
class Context:
    def __init__(self, bot: SignalBot, message: Message) -> None:
        ...
    
    async def send(self, text: str, *, base64_attachments: list[str] | None = ..., link_preview: LinkPreview | None = ..., mentions: list[dict[str, Any]] | None = ..., text_mode: str | None = ..., view_once: bool = ...) -> int:
        ...
    
    async def edit(self, text: str, edit_timestamp: int, *, base64_attachments: list[str] | None = ..., link_preview: LinkPreview | None = ..., mentions: list[dict[str, Any]] | None = ..., text_mode: str | None = ..., view_once: bool = ...) -> int:
        ...
    
    async def reply(self, text: str, *, base64_attachments: list[str] | None = ..., link_preview: LinkPreview | None = ..., mentions: (list[dict[str, Any]] | None) = ..., text_mode: str | None = ..., view_once: bool = ...) -> int:
        ...
    
    async def react(self, emoji: str) -> None:
        ...
    
    async def receipt(self, receipt_type: Literal["read", "viewed"]) -> None:
        ...
    
    async def start_typing(self) -> None:
        ...
    
    async def stop_typing(self) -> None:
        ...
    
    async def remote_delete(self, timestamp: int) -> int:
        ...
    


