"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import TYPE_CHECKING
from signalbot.link_previews import LinkPreview
from signalbot.quote import Quote
from signalbot.api import SignalAPI

if TYPE_CHECKING:
    ...
class MessageType(Enum):
    SYNC_MESSAGE = ...
    DATA_MESSAGE = ...
    EDIT_MESSAGE = ...
    DELETE_MESSAGE = ...


class Message:
    def __init__(self, source: str, source_number: str | None, source_uuid: str, timestamp: int, message_type: MessageType, text: str, *, base64_attachments: list[str] | None = ..., attachments_local_filenames: list[str] | None = ..., view_once: bool = ..., link_previews: list[LinkPreview] | None = ..., group: str | None = ..., reaction: str | None = ..., mentions: list[str] | None = ..., quote: Quote | None = ..., target_sent_timestamp: int | None = ..., remote_delete_timestamp: int | None = ..., raw_message: str | None = ...) -> None:
        ...
    
    def recipient(self) -> str:
        ...
    
    def is_private(self) -> bool:
        ...
    
    def is_group(self) -> bool:
        ...
    
    @classmethod
    async def parse(cls, signal: SignalAPI, raw_message_str: str) -> Message:
        ...
    
    def __str__(self) -> str:
        ...
    


class UnknownMessageFormatError(Exception):
    ...


