"""
This type stub file was generated by pyright.
"""

from typing import Any
from pydantic import BaseModel

class Quote(BaseModel):
    model_config = ...
    id: int
    author: str
    author_number: str
    author_uuid: str
    text: str
    attachments: list[dict[str, Any]]


