"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any

class Storage(ABC):
    @abstractmethod
    def exists(self, key: str) -> bool:
        ...
    
    @abstractmethod
    def read(self, key: str) -> Any:
        ...
    
    @abstractmethod
    def save(self, key: str, object: Any) -> None:
        ...
    
    @abstractmethod
    def delete(self, key: str) -> None:
        ...
    


class StorageError(Exception):
    ...


class SQLiteStorage(Storage):
    def __init__(self, database: str = ..., **kwargs) -> None:
        ...
    
    def exists(self, key: str) -> bool:
        ...
    
    def read(self, key: str) -> Any:
        ...
    
    def save(self, key: str, object: Any) -> None:
        ...
    
    def delete(self, key: str) -> None:
        ...
    


class RedisStorage(Storage):
    def __init__(self, host: str, port: int) -> None:
        ...
    
    def exists(self, key: str) -> bool:
        ...
    
    def read(self, key: str) -> Any:
        ...
    
    def save(self, key: str, object: Any) -> None:
        ...
    
    def delete(self, key: str) -> None:
        ...
    


